/** @jsxRuntime classic */
import React, { useEffect, useState } from 'react';
const base='/_emdash/api/plugins/northfield-enquiries/';
async function api(route:string,body?:unknown){const response=await fetch(base+route,{method:body?'POST':'GET',headers:{'X-EmDash-Request':'1',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok)throw new Error(response.status===403?'Editor permission is required to access private enquiries.':'The request could not be completed.');const result=await response.json();if(!result.data?.ok)throw new Error('The record changed or could not be saved. Refresh and try again.');return result.data;}
function Inbox(){const [items,setItems]=useState<any[]>([]),[agents,setAgents]=useState<any[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
const load=async()=>{try{const data=await api('list');setItems(data.items);setAgents(data.agents);setError('');}catch(e){setError((e as Error).message);}};
useEffect(()=>{load();},[]);
const save=async(item:any,remove=false)=>{setBusy(true);try{if(remove){if(!window.confirm('Permanently delete this test enquiry?'))return;await api('delete',{id:item.id,revision:item.revision});}else await api('update',{id:item.id,revision:item.revision,status:item.data.status,assignedTo:item.data.assignedTo});setNotice(remove?'Enquiry deleted.':'Enquiry updated.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
return <div style={{padding:28,maxWidth:1100}}><h1 style={{fontSize:28,marginBottom:12}}>Private enquiries</h1><p>Editor and Admin only. Test notifications are captured locally for enquiries@northfield.example; nothing is emailed. Use fictional personal details.</p><button onClick={load} disabled={busy} style={{margin:'18px 0'}}>Refresh inbox</button><p role="alert">{error}</p><p role="status">{notice}</p>{!items.length&&!error&&<p>No test enquiries yet.</p>}{items.map((item,index)=><article key={item.id} style={{border:'1px solid #bbc5bd',padding:24,marginBottom:24,borderRadius:8}}><h2 style={{fontSize:21}}>{item.data.kind} · {item.data.name}</h2><p>{item.data.createdAt} · {item.data.email} · {item.data.phone}</p>{item.data.propertyTitle&&<p>Property: {item.data.propertyTitle}</p>}{item.data.address&&<p>Address: {item.data.address} · {item.data.intention}</p>}<p style={{whiteSpace:'pre-wrap',margin:'16px 0'}}>{item.data.message}</p><div style={{display:'flex',gap:20,flexWrap:'wrap'}}><label>Status <select value={item.data.status} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,data:{...x.data,status:e.target.value}}:x))}>{['New','In progress','Closed'].map(s=><option key={s}>{s}</option>)}</select></label><label>Assigned colleague <select value={item.data.assignedTo} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,data:{...x.data,assignedTo:e.target.value}}:x))}><option value="">Unassigned</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button onClick={()=>save(item)} disabled={busy}>Save</button><button onClick={()=>save(item,true)} disabled={busy}>Delete test data</button></div><details style={{marginTop:18}}><summary>Captured test email</summary><p>To: {item.data.notification.to}</p><p>{item.data.notification.subject}</p><p>{item.data.notification.body}</p><p>Delivery: {item.data.notification.delivery}</p></details></article>)}</div>;
}
export const pages={'/inbox':Inbox};
