// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock, ReferencePage } from "emdash";

export interface Agent {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  role?: string;
  initials?: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Area {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  eyebrow?: string;
  excerpt?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  content?: PortableTextBlock[];
  highlights?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Article {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  eyebrow?: string;
  excerpt?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  content?: PortableTextBlock[];
  category?: string;
  read_time?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Branch {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  eyebrow?: string;
  excerpt?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  content?: PortableTextBlock[];
  address?: string;
  phone?: string;
  email?: string;
  hours?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface PageLayoutHeroV1Block {
  _type: "hero";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "heading"?: string | null;
  "text"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "link"?: string | null;
  "label"?: string | null;
}

export type PageLayoutHeroBlock = PageLayoutHeroV1Block;

export interface PageLayoutTextImageV1Block {
  _type: "text_image";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "heading"?: string | null;
  "text"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "link"?: string | null;
  "label"?: string | null;
}

export type PageLayoutTextImageBlock = PageLayoutTextImageV1Block;

export interface PageLayoutPropertyGridV1Block {
  _type: "property_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "heading"?: string | null;
  "text"?: string | null;
  "market"?: "all" | "sale" | "let" | null;
  "limit"?: number | null;
  "link"?: string | null;
  "label"?: string | null;
}

export type PageLayoutPropertyGridBlock = PageLayoutPropertyGridV1Block;

export interface PageLayoutAreaCardsV1Block {
  _type: "area_cards";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "heading"?: string | null;
  "text"?: string | null;
}

export type PageLayoutAreaCardsBlock = PageLayoutAreaCardsV1Block;

export interface PageLayoutTeamGridV1Block {
  _type: "team_grid";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "heading"?: string | null;
  "text"?: string | null;
}

export type PageLayoutTeamGridBlock = PageLayoutTeamGridV1Block;

export interface PageLayoutTestimonialsV1Block {
  _type: "testimonials";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "heading"?: string | null;
  "items"?: { "quote"?: string | null; "name"?: string | null; "detail"?: string | null }[] | null;
}

export type PageLayoutTestimonialsBlock = PageLayoutTestimonialsV1Block;

export interface PageLayoutFaqsV1Block {
  _type: "faqs";
  _version: 1;
  _key: string;
  "heading"?: string | null;
  "items"?: { "question"?: string | null; "answer"?: string | null }[] | null;
}

export type PageLayoutFaqsBlock = PageLayoutFaqsV1Block;

export interface PageLayoutCtaV1Block {
  _type: "cta";
  _version: 1;
  _key: string;
  "eyebrow"?: string | null;
  "heading"?: string | null;
  "text"?: string | null;
  "link"?: string | null;
  "label"?: string | null;
}

export type PageLayoutCtaBlock = PageLayoutCtaV1Block;

export type PageLayoutBlock = PageLayoutHeroBlock | PageLayoutTextImageBlock | PageLayoutPropertyGridBlock | PageLayoutAreaCardsBlock | PageLayoutTeamGridBlock | PageLayoutTestimonialsBlock | PageLayoutFaqsBlock | PageLayoutCtaBlock;

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  excerpt?: string;
  layout?: PageLayoutBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Property {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  reference: string;
  market?: "sale" | "let";
  price: number;
  qualifier?: "Guide price" | "Offers over" | "Fixed price" | "Per calendar month";
  availability?: "Available" | "Under offer" | "Sold STC" | "Sold" | "Let agreed" | "Let";
  property_type?: "Detached" | "Semi-detached" | "Terraced" | "Apartment" | "Cottage";
  bedrooms?: number;
  bathrooms?: number;
  floor_area?: number;
  tenure?: "Freehold" | "Leasehold" | "Rental";
  council_tax?: string;
  deposit?: number;
  address?: string;
  location?: string;
  postcode?: string;
  latitude?: number;
  longitude?: number;
  excerpt?: string;
  description?: PortableTextBlock[];
  features?: { "text"?: string | null }[];
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  gallery?: { "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null; "caption"?: string | null }[];
  brochure?: { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };
  epc?: { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };
  epc_rating?: string;
  video_link?: string;
  featured?: boolean;
  floorplan?: { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };
  floorplans?: { "title"?: string | null; "url"?: string | null }[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface SiteContent {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  demo_notice?: string;
  footer_text?: string;
  strapline?: string;
  valuation_label?: string;
  shared_cta_heading?: string;
  shared_cta_text?: string;
  shared_cta_label?: string;
  ui?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface AgentReferences {
  branch: ReferencePage<Branch>;
}

export interface ArticleReferences {
  author: ReferencePage<Agent>;
}

export interface PropertyReferences {
  branch: ReferencePage<Branch>;
  agent: ReferencePage<Agent>;
  area: ReferencePage<Area>;
}

declare module "emdash" {
  interface EmDashCollections {
    agents: Agent;
    areas: Area;
    articles: Article;
    branches: Branch;
    pages: Page;
    posts: Post;
    properties: Property;
    site_content: SiteContent;
  }
  interface EmDashCollectionReferences {
    agents: AgentReferences;
    articles: ArticleReferences;
    properties: PropertyReferences;
  }
}