import json
from pathlib import Path

def field(slug,t='string',label=None,**kw):return dict(slug=slug,label=label or slug.replace('_',' ').title(),type=t,**kw)
def select(s,opts):return field(s,'select',validation={'options':opts})
def ref(s,target):return field(s,'reference',validation={'targetCollection':target,'multiple':False})
def repeat(s,fields):return field(s,'repeater',validation={'subFields':fields})
def pt(s):return [{'_type':'block','_key':'p'+str(i),'style':'normal','children':[{'_type':'span','_key':'s'+str(i),'text':p,'marks':[]}],'markDefs':[]} for i,p in enumerate(s.split('\n\n'))]
photos=['photo-1600596542815-ffad4c1539a9','photo-1600585154340-be6161a56a0c','photo-1600047509807-ba8f99d2cdde','photo-1600607687920-4e2a09cf159d','photo-1600566753086-00f18fb6b3ea','photo-1518837695005-2083093ee35b','photo-1449844908441-8829872d2607','photo-1511818966892-d7d671e672a2']
def img(i,alt='Illustrative stock photograph; not an actual property offered for sale'):
 return {'$media':{'url':'https://images.unsplash.com/'+photos[i%len(photos)]+'?auto=format&fit=crop&w=1440&q=80','alt':alt,'filename':'northfield-'+str(i%len(photos))+'.jpg'}}
def entry(slug,data,status='published'):return {'id':slug,'slug':slug,'status':status,'data':data}
def block(t,**data):return dict(_type=t,_version=1,_key=t+'-'+str(len(data))+str(len(str(data))),**data)
common=[field('title',required=True),field('eyebrow'),field('excerpt','text'),field('image','image'),field('content','portableText')]
collections=[]
def col(slug,fields,url=None):
 collections.append(dict(slug=slug,label=slug.replace('_',' ').title(),labelSingular={'properties':'Property','branches':'Branch','agents':'Agent','areas':'Area','articles':'Article','pages':'Page','site_content':'Site content'}[slug],supports=['drafts','revisions','preview','search','seo'],fields=fields,**({'urlPattern':url} if url else {})))
col('areas',common+[field('highlights','text')],'/areas/{slug}')
col('branches',common+[field('address','text'),field('phone'),field('email'),field('hours','text')],'/branches/{slug}')
col('agents',[field('title',required=True),field('role'),field('initials'),field('content','portableText'),ref('branch','branches')])
col('properties',[field('title',required=True),field('reference',required=True),select('market',['sale','let']),field('price','number',required=True),select('qualifier',['Guide price','Offers over','Fixed price','Per calendar month']),select('availability',['Available','Under offer','Sold STC','Sold','Let agreed','Let']),select('property_type',['Detached','Semi-detached','Terraced','Apartment','Cottage']),field('bedrooms','integer'),field('bathrooms','integer'),field('floor_area','number'),select('tenure',['Freehold','Leasehold','Rental']),field('council_tax'),field('deposit','number'),field('address','text'),field('location'),field('postcode'),field('latitude','number'),field('longitude','number'),field('excerpt','text'),field('description','portableText'),repeat('features',[field('text')]),field('image','image'),repeat('gallery',[field('image','image'),field('caption')]),field('floorplan','file'),repeat('floorplans',[field('title'),field('url','url')]),field('brochure','file'),field('epc','file'),field('epc_rating'),field('video_link','url'),ref('branch','branches'),ref('agent','agents'),ref('area','areas'),field('featured','boolean')],'/properties/{slug}')
blockfields={
'hero':[field('eyebrow'),field('heading'),field('text','text'),field('image','image'),field('link'),field('label')],
 'text_image':[field('eyebrow'),field('heading'),field('text','text'),field('image','image'),field('link'),field('label')],
 'property_grid':[field('eyebrow'),field('heading'),field('text','text'),select('market',['all','sale','let']),field('limit','integer'),field('link'),field('label')],
 'area_cards':[field('eyebrow'),field('heading'),field('text','text')],
 'team_grid':[field('eyebrow'),field('heading'),field('text','text')],
 'testimonials':[field('eyebrow'),field('heading'),repeat('items',[field('quote','text'),field('name'),field('detail')])],
 'faqs':[field('heading'),repeat('items',[field('question'),field('answer','text')])],
 'cta':[field('eyebrow'),field('heading'),field('text','text'),field('link'),field('label')],
}
col('pages',[field('title',required=True),field('excerpt','text'),field('layout','blocks',validation={'allowedTypes':list(blockfields),'maxItems':20}),field('content','portableText')],'/{slug}')
col('articles',common+[field('category'),field('read_time'),ref('author','agents')],'/advice/{slug}')
col('site_content',[field('title',required=True),field('demo_notice','text'),field('footer_text','text'),field('strapline'),field('valuation_label'),field('shared_cta_heading'),field('shared_cta_text','text'),field('shared_cta_label'),field('ui','json')])
content={c['slug']:[] for c in collections}
areas=[('alderwick','Alderwick','Village life, with room to breathe.',0,'Leafy lanes, an independent high street and open countryside on your doorstep.'),('mereford','Mereford','A fresh perspective on town living.',6,'Riverside walks, neighbourhood cafés and characterful streets made for exploring.'),('bracken-hill','Bracken Hill','A little closer to the countryside.',2,'Generous gardens, quiet corners and a slower pace, without feeling far from everything.')]
for slug,title,excerpt,im,body in areas:content['areas'].append(entry(slug,dict(title=title,eyebrow='THE NORTHFIELD NOTEBOOK',excerpt=excerpt,image=img(im),content=pt(body+'\n\nThis is an invented neighbourhood for our CMS demonstration. Local amenities, descriptions and property addresses are fictional, rather than guidance about a real place.'),highlights='Independent shops · Green spaces · Community spirit')))
for slug,title,address in [('alderwick-office','Alderwick branch','14 Market Lane, Alderwick, NF1 2AB'),('mereford-office','Mereford branch','8 Riverside Walk, Mereford, NF2 3CD')]:
 content['branches'].append(entry(slug,dict(title=title,eyebrow='YOUR LOCAL TEAM',excerpt='Good advice starts with a conversation.',image=img(6 if slug.startswith('mere') else 7),content=pt('Our fictional local team brings a thoughtful, personal approach to every move. From a first conversation to the final handover, you will always know who to turn to.'),address=address,phone='01632 960123' if slug.startswith('alder') else '01632 960124',email='hello@northfield.example',hours='Monday–Friday 9am–5.30pm\nSaturday 9am–1pm\nSunday closed')))
for i,(slug,name,role) in enumerate([('eleanor-hart','Eleanor Hart','Director & sales specialist'),('james-whitmore','James Whitmore','Lettings manager'),('maya-ellis','Maya Ellis','Senior property adviser'),('oliver-reed','Oliver Reed','Property adviser')]):
 content['agents'].append(entry(slug,dict(title=name,role=role,initials=''.join(p[0] for p in name.split()),content=pt('A fictional member of the Northfield team, here to demonstrate agent profiles, branch relationships and enquiry assignment.'),branch='$ref:'+('alderwick-office' if i<2 else 'mereford-office'))))
names=['The Old Rectory','Willow House','The Coach House','The Garden Apartment','Rose Cottage','Oakfield House','The Courtyard','Meadow View','The Paddocks','The Mill House','Fern Lodge','Orchard End','The Gables','Cedar House','The Croft','Lime Tree House','The Granary','Hazel Cottage','The Loft','Field End','Birch House','The Old School','Westbrook','The Terrace','Ashdown','Bramble Cottage','The Green','Millbank','The Corner House','Maple Lodge']
for i,name in enumerate(names):
 area=areas[i%3]; market='let' if i>=20 else 'sale'; beds=2+i%4; typ=['Detached','Semi-detached','Terraced','Apartment','Cottage'][i%5]; slug=name.lower().replace(' ','-'); price=([795000,625000,485000,295000,425000,895000][i%6]+(i//6)*15000) if market=='sale' else 950+(i%7)*175
 availability='Sold STC' if i==7 else 'Sold' if i==14 else 'Let agreed' if i==24 else 'Available'
 data=dict(title=name,reference=f'NC{1001+i}',market=market,price=price,qualifier='Guide price' if market=='sale' else 'Per calendar month',availability=availability,property_type=typ,bedrooms=beds,bathrooms=1+i%3,floor_area=85+i*5,tenure='Rental' if market=='let' else 'Leasehold' if typ=='Apartment' else 'Freehold',council_tax='D (illustrative)',deposit=price*5*12/52 if market=='let' else 0,address=f'{i+1} {"Meadow Lane" if i%2 else "Orchard Road"}, {area[1]}',location=area[1],postcode=f'NF{i%3+1} {i%9+1}AB',latitude=53.80+i*.001,longitude=-1.55-i*.001,excerpt='Thoughtfully proportioned spaces, natural light and a setting to make your own.',description=pt(f'A welcoming {beds}-bedroom {typ.lower()} in our fictional {area[1]} neighbourhood. Light-filled living spaces open onto a private garden, with thoughtful details and plenty of flexibility for everyday life.\n\nThe ground floor offers an inviting entrance, a generous living room and an open kitchen and dining space. Upstairs, comfortable bedrooms and well-planned bathrooms make this a home with room to settle in.\n\nFICTIONAL DEMO LISTING. Photographs are illustrative stock imagery and do not depict the stated address. Prices, dimensions, coordinates, floorplans and energy information are invented. No property is being offered for sale or let.'),features=[{'text':t} for t in ['Light-filled living spaces','Private garden or terrace','Flexible home-working space','Characterful surroundings','Illustrative listing only']],image=img(i%5),gallery=[{'image':img(i%5),'caption':'Exterior · illustrative stock photograph'},{'image':img(3),'caption':'Living space · illustrative stock photograph'},{'image':img(4),'caption':'Interior · illustrative stock photograph'}],floorplans=[],epc_rating=['B','C','D'][i%3],branch='$ref:'+('alderwick-office' if i%3==0 else 'mereford-office'),agent='$ref:'+['eleanor-hart','james-whitmore','maya-ellis','oliver-reed'][i%4],area='$ref:'+area[0],featured=i in [0,1,2,20])
 content['properties'].append(entry(slug,data))
cta=block('cta',eyebrow='YOUR NEXT CHAPTER',heading='',text='',link='/valuation',label='')
content['pages']=[entry('home',{'title':'A place to call your own','excerpt':'Thoughtful property advice. A genuinely personal approach.','layout':[block('hero',eyebrow='INDEPENDENT MINDS. LOCAL ROOTS.',heading='A place to call\nyour own.',text='Remarkable homes. Familiar faces. A thoughtful approach to your next move.',image=img(0),link='/sales',label='Explore our homes'),block('property_grid',eyebrow='A FEW OF OUR FAVOURITES',heading='Homes with a little more heart.',text='Discover a selection of places we would love to show you.',market='sale',limit=3,link='/sales',label='View all properties'),block('text_image',eyebrow='THE NORTHFIELD WAY',heading='Property is personal.\nSo are we.',text='A home is more than an address. It is the start of something. We take time to understand what matters to you, pairing local knowledge with honest, considered advice.',image=img(4),link='/about',label='Get to know us'),block('area_cards',eyebrow='FIND YOUR KIND OF NEIGHBOURHOOD',heading='Local places. Lasting connections.',text='A feel for the places you could call home.'),block('testimonials',eyebrow='KIND WORDS',heading='A move worth talking about.',items=[{'quote':'From our first conversation, we felt listened to. Clear advice, thoughtful details and a team who made time for us.','name':'Anna & Ben','detail':'Fictional seller testimonial'}]),cta]}),]
for slug,title,eyebrow,body in [('selling','A considered approach to selling.','SELL WITH NORTHFIELD','From thoughtful presentation to clear communication, we shape a plan around your home and your priorities. Our fictional service demonstrates editable agency content, valuation enquiries and shared page sections.'),('letting','Your property. In good hands.','LET WITH NORTHFIELD','Whether you are letting your first home or reviewing a portfolio, we begin by understanding what you need. This demo illustrates a lettings service page; it does not offer a real managed service.'),('about','Local roots. A fresh outlook.','MEET NORTHFIELD & CO.','An independent estate agency built on a simple idea: good property advice should feel personal. Northfield & Co. is a fictional brand created to explore a modern content management workflow.'),('valuation','Every move starts with a conversation.','REQUEST A VALUATION','Tell us a little about your property. This is a fictional demonstration: submissions are stored privately for testing and do not book a real valuation.'),('contact','Let’s talk about your next chapter.','GET IN TOUCH','Visit our fictional branches, meet the team or send a test enquiry. Please use invented contact details when trying this demo.'),('sales','Find your next place.','HOMES FOR SALE','Discover characterful homes across our fictional neighbourhoods.'),('lettings','Room for your next chapter.','HOMES TO RENT','Explore our collection of fictional rental homes.'),('areas','Somewhere that feels like you.','OUR AREA GUIDES','Get a feel for our three fictional neighbourhoods.'),('branches','Local knowledge, at your door.','OUR BRANCHES','Two fictional branches. One thoughtful approach.'),('advice','A little clarity for your next move.','THE NORTHFIELD JOURNAL','Ideas and practical perspectives for the journey ahead.'),('privacy','Your information, handled thoughtfully.','DEMO PRIVACY NOTICE','This local demo stores test enquiry details, enquiry status and assignment in private plugin storage. Use fictional names and contact information. No customer accounts, advertising analytics or real email delivery are enabled. The operator can remove test submissions from the private inbox. This demonstration notice needs a legal and operational review before any public deployment.'),('cookies','A quieter kind of browsing.','COOKIE INFORMATION','Public pages use no advertising or analytics cookies. Essential session cookies support EmDash sign-in and preview workflows. External stock photography is imported into local media storage. External map and video links load only when you choose to open them.'),('404','This one seems to have moved.','PAGE NOT FOUND','The address you followed does not exist. Let’s help you find your way home.')]:
 layout=[] if slug in ['sales','lettings','areas','branches','advice','404'] else [block('hero',eyebrow=eyebrow,heading=title,text=body,image=img(1 if slug=='selling' else 4),link='',label='')]
 if slug in ['selling','letting']:layout += [block('text_image',eyebrow='START WITH A CLEAR PLAN',heading='Good advice.\nAt every step.',text='Presentation, communication and a plan that makes sense for you. We explain the next step, keep you informed and make space for your questions.',image=img(3),link='/valuation',label='Talk to the team'),block('faqs',heading='A few things you might be wondering.',items=[{'question':'How do I arrange a valuation?','answer':'Complete the demonstration form. It records a private test enquiry; no appointment is scheduled.'},{'question':'Are these real homes?','answer':'No. Every listing and address is fictional. Stock images are illustrative.'}]),cta]
 if slug=='about':layout += [block('team_grid',eyebrow='PEOPLE, FIRST',heading='Familiar faces. Fresh thinking.',text='Meet our fictional team.'),cta]
 content['pages'].append(entry(slug,dict(title=title,excerpt=body,layout=layout,content=pt(body))))
for i,(slug,title,category,body) in enumerate([('preparing-your-home','The art of a welcoming first impression','SELLING','Start with the spaces you use every day. A clear entrance, natural light and small finishing touches help a home feel welcoming.\n\nThis illustrative editorial article demonstrates rich-text editing and publishing in EmDash. It is not professional valuation or legal advice.'),('finding-your-neighbourhood','Finding a neighbourhood that feels like you','LOCAL LIFE','Think about the shape of your day: the morning walk, the shops you return to and where you like to spend a quiet hour. A neighbourhood is more than its postcode.\n\nOur area guides describe invented places for this demo. Visit real areas and verify amenities independently when planning a move.'),('rental-viewing-notes','Make room for the right questions','LETTINGS','A viewing is a chance to understand how a space might work for you. Take time to notice the light, storage and layout, and keep a note of questions for the agent.\n\nThis is demonstration copy, not current legal or tenancy guidance.')]):content['articles'].append(entry(slug,dict(title=title,eyebrow=category,excerpt=body.split('\n')[0],content=pt(body),image=img(i+2),category=category,read_time='3 minute read',author='$ref:eleanor-hart')))
ui=dict(search='Find a home',sale='Buy',let='Rent',location='Location',any_location='All locations',min_price='Min. price',max_price='Max. price',any_price='No preference',bedrooms='Bedrooms',any_bedrooms='Any bedrooms',property_type='Property type',any_type='All types',sort='Sort by',newest='Recently added',price_asc='Price: low to high',price_desc='Price: high to low',search_button='Show properties',reset='Clear filters',results='properties',no_results='No homes match this search. Try broadening your filters.',next='Next',previous='Previous',view_property='Discover this home',beds='bedrooms',baths='bathrooms',area_unit='sq m',back_search='Back to properties',key_features='The finer details',description='A little more about this home',gallery='Gallery',floorplan='Illustrative floorplan (PDF)',floorplans='Floorplans & documents',brochure='Property brochure',epc='Energy performance',map='View illustrative location',video='Watch property video',viewing='Come and take a look.',viewing_text='Send a private test viewing enquiry to our team.',name='Your name',email='Email address',phone='Phone number',message='A little more about your plans',address='Property address',consent='I have read the privacy notice and understand this is a fictional demo.',submit='Send test enquiry',success='Thank you. Your test enquiry has been stored privately. No real appointment or email has been sent.',error='Please check the highlighted details and try again.',form_note='Use fictional details. No real appointments or emails.',valuation_type='I am thinking of',selling='Selling',letting='Letting',contact='Contact',branch='Your local branch',agent='Your property adviser',availability='Availability',tenure='Tenure',council_tax='Council tax',deposit='Deposit',reference='Reference',floor_area='Floor area',epc_rating='EPC rating',fictional='Fictional demo property · stock imagery',menu='Menu',skip='Skip to content',home='Home',all_advice='All advice',read_article='Read the story',hours='Opening hours',team='Our team',contact_team='Meet your local team',close='Close',image_next='Next photograph',image_previous='Previous photograph',image_open='Open photograph',demo_documents='Illustrative documents only. Not valid for property transactions.',privacy='Privacy',cookies='Cookies',copyright='Northfield & Co. · Fictional demonstration',enquiry_status='Enquiry status')
content['site_content']=[entry('global',dict(title='Shared site content',demo_notice='FICTIONAL DEMO — properties, people and places are illustrative. No real transactions.',footer_text='Independent minds. Local roots. A thoughtful approach to your next move.',strapline='ESTATE AGENTS · SALES & LETTINGS',valuation_label='Book a valuation',shared_cta_heading='Your next chapter starts here.',shared_cta_text='Curious about your home’s next move? Let’s begin with a conversation.',shared_cta_label='Arrange a valuation',ui=ui))]
seed=dict(version='1',meta={'name':'Northfield & Co.','description':'Fictional UK estate agency demo'},settings={'title':'Northfield & Co.','tagline':'Independent minds. Local roots.','timezone':'Europe/London'},collections=collections,blockTypes=[dict(slug=k,label=k.replace('_',' ').title(),currentVersion=1,versions=[dict(version=1,fields=v)]) for k,v in blockfields.items()],content=content,menus=[dict(name='primary',label='Primary navigation',items=[dict(type='custom',label=l,url=u) for l,u in [('Buy','/sales'),('Rent','/lettings'),('Sell','/selling'),('Let','/letting'),('Our areas','/areas'),('About us','/about')]]),dict(name='footer',label='Footer navigation',items=[dict(type='custom',label=l,url=u) for l,u in [('Our branches','/branches'),('Journal','/advice'),('Contact','/contact'),('Privacy','/privacy'),('Cookies','/cookies')]])])
Path('seed/seed.json').write_text(json.dumps(seed,indent=2)+'\n')
print('Generated',len(content['properties']),'properties;',len(collections),'collections;',len(blockfields),'block types')
